[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = [
    "winnt",
    "libloaderapi",
    "processthreadsapi",
    "fileapi",
    "errhandlingapi",
    "minwindef"
]}

[dev-dependencies]
rstest = "0.18"
